In [9]:
import pandas as pd 

# 导入数据
data = pd.read_csv("eurostat/animal_geo_ok/1980.csv")

In [10]:
# 查看数据
data.head()

,country,country_label,state,state_label,county,county_label,unit_label,year,Dairy cows,Beef cattle,excl cattle,"Fattening pigs, live weight 50 kg or over",Sheep,County Layers,County broiler
0,AT,Austria,AT1,Ostösterreich,AT11,Burgenland (AT),Thousand heads (animals),1980,NaN,0.0,NaN,NaN,2.4,NaN,NaN
1,AT,Austria,AT1,Ostösterreich,AT12,Niederösterreich,Thousand heads (animals),1980,NaN,0.0,NaN,NaN,31.0,NaN,NaN
2,AT,Austria,AT1,Ostösterreich,AT13,Wien,Thousand heads (animals),1980,NaN,0.0,NaN,NaN,0.4,NaN,NaN
3,AT,Austria,AT2,Südösterreich,AT21,Kärnten,Thousand heads (animals),1980,NaN,0.0,NaN,NaN,26.8,NaN,NaN
4,AT,Austria,AT2,Südösterreich,AT22,Steiermark,Thousand heads (animals),1980,NaN,0.0,NaN,NaN,31.2,NaN,NaN

In [12]:



bx_data = pd.read_excel("巴西/农作物_fao_ok/2022_.xlsx")

In [13]:
bx_data.head()

,Nível,Cód.,Município,Feijão (em grão),花生,马铃薯,Milho (em grão),Abacaxi*,Alfafa fenada,Algodão herbáceo (em caroço),...,Noz (fruto seco),Palmito,Pera,Pêssego,Pimenta-do-reino,Sisal ou agave (fibra),Tangerina,Tungue (fruto seco),Urucum (semente),Uva
0,MU,1100015,Alta Floresta D'Oeste (RO),480,..,..,5556,100,...,-,...,-,-,-,-,-,-,4,-,-,-
1,MU,1100023,Ariquemes (RO),1,..,..,11400,416,...,-,...,-,-,-,-,-,-,-,-,12,-
2,MU,1100031,Cabixi (RO),...,..,..,96948,55,...,-,...,-,-,-,-,-,-,-,-,100,-
3,MU,1100049,Cacoal (RO),60,..,..,5280,1955,...,-,...,-,-,-,-,14,-,26,-,16,-
4,MU,1100056,Cerejeiras (RO),3,..,..,138819,505,...,-,...,-,-,-,-,-,-,-,-,18,-

In [20]:
# 提取FAO巴西农作物数据
data = pd.read_csv('faostat_HGU/Production/Crops and livestock products/Production_Quantity/Crops_primary/2022.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'faostat_HGU/Production/Crops and livestock products/Production_Quantity/Crops_primary/2022.csv'

In [18]:
new_data = data[data['Area']=='Brazil']

In [19]:
new_data.to_csv('校对总量全（新）/巴西/FAO/农作物/1974.csv', index=False)