In [1]:
import usda_quickstats as stat
import pandas as pd
import re
import matplotlib.pyplot as plt

In [5]:
stat.Key_init("7BF5BA5C-D7DA-356F-8412-A4710CAE3113")

API Key initialized successfully

In [6]:
plt.rcParams["font.sans-serif"] = ["simhei"]

# 数据下载

In [3]:
State = stat.get_par("state_name")

# 需要下载的数据有：
### 1、state:动物的poultry(program:survey)slaughtered，无inventory
### 2、state:动物的livestock(program:survey)slaughtered 无inv...
### 3、county:动物的poultry(program:census)inventory
### 4、county:动物的livestock(program:census)inventory

## 下载第三个

In [22]:
# 下载county的动物的poultry,后续记得删除poultry total
# GROUP选择了poultry
params = {
    "source_desc":"CENSUS",
    "sector_desc":"ANIMALS & PRODUCTS",
    "group_desc":"POULTRY",
#     "commodity_desc":["CHICKENS","DUCKS","EGGS","MEAL","POULTRY BY-PRODUCT MEALS",
#                      "POULTRY FATS","POULTRY TOTALS","POULTRY, OTHER","TURKEYS"],
    "statisticcat_desc":["INVENTORY"],
#     "short_desc":["CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN HEAD",
#                   "CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB / HEAD, LIVE BASIS",
#                  "CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB, LIVE BASIS",
#                  "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN HEAD",
#                   "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB / HEAD, LIVE BASIS",
#                  "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB, LIVE BASIS"],
    "agg_level_desc":"COUNTY",
}

In [23]:
stat.get_par(params)

TypeError: unhashable type: 'dict'

In [ ]:
# 若总数据不大于5万，则一起下载
for year in range(1924,2023):
    params["year"]=str(year)
    data=stat.get_data(params)
    # 删除不要的列
    columns_to_drop = ["begin_code","load_time","end_code","congr_district_code"]
    data.drop(columns_to_drop, axis=1, inplace=True)
    data.to_csv("D:/中科院数据下载/quickstats/county/poultry/"+str(year)+".csv",index=False)

In [5]:
# data_all = pd.DataFrame()
# # 数据太多了，所以按照州的五个五个下载，再用python合并
# for i in range(0,State.shape[0],5):
#     last = min(State.shape[0],i+4)
#     params["state_name"] = list(State.loc[i:last].state_name)
#     data = stat.get_data(params)
#     print(data.shape[0])
    
#     # 将所有州合在一起，形成一个DF，最后再按照年划分
#     data_all = pd.concat([data_all,data],axis=0) # 按行合并
data_all = pd.DataFrame()
# 数据太多了，所以按照州的一个一个下载，再用python合并
for i in range(State.shape[0]):
    params["state_name"] = State.loc[i].state_name
    data = stat.get_data(params)
    print(str(State.loc[i].state_name)+":"+str(data.shape[0]))
    
    # 将所有州合在一起，形成一个DF，最后再按照年划分
    data_all = pd.concat([data_all,data],axis=0) # 按行合并

ALABAMA:6791
ALASKA:453
Response code 400: bad request - invalid query
AMERICAN SAMOA:0
ARIZONA:1578
ARKANSAS:6729
CALIFORNIA:6027
COLORADO:5200
CONNECTICUT:996
DELAWARE:335
FLORIDA:6702
GEORGIA:11724
Response code 400: bad request - invalid query
GUAM:0
HAWAII:410
IDAHO:3746
ILLINOIS:9147
INDIANA:8491
IOWA:9438
KANSAS:8364
KENTUCKY:10839
LOUISIANA:4951
MAINE:1664
MARYLAND:2322
MASSACHUSETTS:1385
MICHIGAN:8546
MINNESOTA:8447
MISSISSIPPI:6414
MISSOURI:11095
MONTANA:4454
NEBRASKA:7414
NEVADA:1118
Response code 400: bad request - invalid query
NEW ENGLAND:0
NEW HAMPSHIRE:1069
NEW JERSEY:2194
NEW MEXICO:2894
NEW YORK:6179
NORTH CAROLINA:9008
NORTH DAKOTA:3524
Response code 400: bad request - invalid query
NORTHERN MARIANA ISLANDS:0
OHIO:9517
OKLAHOMA:7804
OREGON:3826
Response code 400: bad request - invalid query
OTHER STATES:0
PENNSYLVANIA:7915
Response code 400: bad request - invalid query
PUERTO RICO:0
RHODE ISLAND:456
SOUTH CAROLINA:4662
SOUTH DAKOTA:4897
TENNESSEE:9630
TEXAS:22648
Response code 400: bad request - invalid query
US TOTAL:0
UTAH:2589
VERMONT:1395
Response code 400: bad request - invalid query
VIRGIN ISLANDS OF THE US:0
VIRGINIA:8531
WASHINGTON:4202
WEST VIRGINIA:4627
WISCONSIN:8056
WYOMING:1993

In [49]:
all = 282396

In [6]:
data_all

,Program,year,Period,Period Type,week_ending,country_name,country_code,state_ansi,state_fips_code,state_alpha,...,Group,Data Item,Zip Code,class_desc,Value,CV (%),begin_code,load_time,end_code,congr_district_code
0,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,POULTRY,"CHICKENS, BROILERS - INVENTORY",,BROILERS,"1,094,358",16.7,12,2018-02-01 00:00:00.000,12,
1,CENSUS,2012,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,POULTRY,"CHICKENS, BROILERS - INVENTORY",,BROILERS,"1,871,616",26.4,12,2012-12-31 00:00:00.000,12,
2,CENSUS,2007,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,POULTRY,"CHICKENS, BROILERS - INVENTORY",,BROILERS,"1,670,490",,12,2012-01-01 00:00:00.000,12,
3,CENSUS,2002,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,POULTRY,"CHICKENS, BROILERS - INVENTORY",,BROILERS,"1,846,500",,12,2012-01-01 00:00:00.000,12,
4,CENSUS,1997,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,POULTRY,"CHICKENS, BROILERS - INVENTORY",,BROILERS,"1,282,775",,12,2012-01-01 00:00:00.000,12,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,CENSUS,1997,END OF DEC,POINT IN TIME,,UNITED STATES,9000,56,56,WY,...,POULTRY,TURKEYS - OPERATIONS WITH INVENTORY,,ALL CLASSES,4,,12,2012-01-01 00:00:00.000,12,
1989,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,56,56,WY,...,POULTRY,TURKEYS - OPERATIONS WITH INVENTORY,,ALL CLASSES,3,(H),12,2018-02-01 00:00:00.000,12,
1990,CENSUS,2012,END OF DEC,POINT IN TIME,,UNITED STATES,9000,56,56,WY,...,POULTRY,TURKEYS - OPERATIONS WITH INVENTORY,,ALL CLASSES,5,26.6,12,2012-12-31 00:00:00.000,12,
1991,CENSUS,2007,END OF DEC,POINT IN TIME,,UNITED STATES,9000,56,56,WY,...,POULTRY,TURKEYS - OPERATIONS WITH INVENTORY,,ALL CLASSES,1,,12,2012-01-01 00:00:00.000,12,
1992,CENSUS,2002,END OF DEC,POINT IN TIME,,UNITED STATES,9000,56,56,WY,...,POULTRY,TURKEYS - OPERATIONS WITH INVENTORY,,ALL CLASSES,1,,12,2012-01-01 00:00:00.000,12,

## 下载第四个

In [196]:
# GROUP选择了livestock
params = {
    "source_desc":"SURVEY",
    "sector_desc":"ANIMALS & PRODUCTS",
    "group_desc":"LIVESTOCK",
    "commodity_desc":["CATTLE","GOATS","HOGS","SHEEP"],
    "statisticcat_desc":["INVENTORY"],
    "short_desc":["CATTLE, CALVES, SLAUGHTER, COMMERCIAL - SLAUGHTERED, MEASURED IN HEAD","CATTLE, CALVES, SLAUGHTER, ON FARM - SLAUGHTERED, MEASURED IN HEAD"],
    "agg_level_desc":"COUNTY"
}

In [197]:
data_all = pd.DataFrame()
# 数据太多了，所以按照州的一个一个下载，再用python合并
for i in range(State.shape[0]):
    params["state_name"] = State.loc[i].state_name
    data = stat.get_data(params)
    print(str(State.loc[i].state_name)+":"+str(data.shape[0]))
    
    # 将所有州合在一起，形成一个DF，最后再按照年划分
    data_all = pd.concat([data_all,data],axis=0) # 按行合并

ALABAMA22729
ALASKA1383
Response code 400: bad request - invalid query
AMERICAN SAMOA0
ARIZONA5425
ARKANSAS24560
CALIFORNIA21991
COLORADO22089
CONNECTICUT2971
DELAWARE1193
FLORIDA21957
GEORGIA47503
Response code 400: bad request - invalid query
GUAM0
HAWAII1648
IDAHO16836
ILLINOIS42182
INDIANA38312
IOWA46953
KANSAS42578
KENTUCKY42333
LOUISIANA18391
MAINE5684
MARYLAND8600
MASSACHUSETTS4183
MICHIGAN33169
MINNESOTA38860
MISSISSIPPI24161
MISSOURI47906
MONTANA21505
NEBRASKA39440
NEVADA5292
Response code 400: bad request - invalid query
NEW ENGLAND0
NEW HAMPSHIRE3527
NEW JERSEY5361
NEW MEXICO11498
NEW YORK22389
NORTH CAROLINA31456
NORTH DAKOTA20265
Response code 400: bad request - invalid query
NORTHERN MARIANA ISLANDS0
OHIO38248
OKLAHOMA30835
OREGON14292
Response code 400: bad request - invalid query
OTHER STATES0
PENNSYLVANIA27876
Response code 400: bad request - invalid query
PUERTO RICO0
RHODE ISLAND1454
SOUTH CAROLINA15382
SOUTH DAKOTA28556
TENNESSEE33625
Response code 413: exceeds limit=50000
TEXAS0
Response code 400: bad request - invalid query
US TOTAL0
UTAH11777
VERMONT5435
Response code 400: bad request - invalid query
VIRGIN ISLANDS OF THE US0
VIRGINIA33495
WASHINGTON14829
WEST VIRGINIA16607
WISCONSIN31869
WYOMING8989

In [ ]:
all = 1149747

In [201]:
# 对于前面按州提取还超额的，再按照年提取
params["state_name"] = "TEXAS"
year=["1997","2002","2007","2012","2017"]
for i in year:
    params["year"] = i
    data_Texas = stat.get_data(params)
    print(data_Texas.shape[0])
    data_all = pd.concat([data_all,data_Texas],axis=0) # 按行合并
# # 按年分类保存成csv文件
# for year,group in data_all.groupby("year"):
#     group.to_csv("D:/中科院数据下载/quickstats/county/livestock/"+str(year)+".csv",index=False)

9324
22758
21625
20097
18344

In [202]:
data_all

,Program,year,Period,Period Type,week_ending,country_name,country_code,state_ansi,state_fips_code,state_alpha,...,Group,Data Item,Zip Code,class_desc,Value,CV (%),begin_code,load_time,end_code,congr_district_code
0,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,LIVESTOCK,"CATTLE, (EXCL COWS) - INVENTORY",,(EXCL COWS),(D),(D),12,2018-02-01 00:00:00.000,12,
1,CENSUS,2012,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,LIVESTOCK,"CATTLE, (EXCL COWS) - INVENTORY",,(EXCL COWS),(D),(D),12,2012-12-31 00:00:00.000,12,
2,CENSUS,2007,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,LIVESTOCK,"CATTLE, (EXCL COWS) - INVENTORY",,(EXCL COWS),508,,12,2012-01-01 00:00:00.000,12,
3,CENSUS,2002,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,LIVESTOCK,"CATTLE, (EXCL COWS) - INVENTORY",,(EXCL COWS),(D),,12,2012-01-01 00:00:00.000,12,
4,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,01,01,AL,...,LIVESTOCK,"CATTLE, (EXCL COWS) - INVENTORY",,(EXCL COWS),579,38.5,12,2018-02-01 00:00:00.000,12,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18339,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,48,48,TX,...,LIVESTOCK,"SHEEP, INCL LAMBS - OPERATIONS WITH INVENTORY",,INCL LAMBS,11,83.4,12,2018-02-01 00:00:00.000,12,
18340,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,48,48,TX,...,LIVESTOCK,"SHEEP, INCL LAMBS - OPERATIONS WITH INVENTORY",,INCL LAMBS,104,83.4,12,2018-02-01 00:00:00.000,12,
18341,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,48,48,TX,...,LIVESTOCK,"SHEEP, INCL LAMBS - OPERATIONS WITH INVENTORY",,INCL LAMBS,381,83.4,12,2018-02-01 00:00:00.000,12,
18342,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,48,48,TX,...,LIVESTOCK,"SHEEP, INCL LAMBS - OPERATIONS WITH INVENTORY",,INCL LAMBS,162,83.4,12,2018-02-01 00:00:00.000,12,
18343,CENSUS,2017,END OF DEC,POINT IN TIME,,UNITED STATES,9000,48,48,TX,...,LIVESTOCK,"SHEEP, INCL LAMBS - OPERATIONS WITH INVENTORY",,INCL LAMBS,8,83.4,12,2018-02-01 00:00:00.000,12,

# 对表头(only county)
### 目的：匹配标准州县名称表格上OBJECTID
无论叫什么名称，都对应到唯一的一个OBJECTID上

In [2]:
import pandas as pd
# 对表头
standard = pd.read_excel("美国标准表头.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '美国标准表头.xlsx'

In [6]:
# 数据导入
data_all = pd.DataFrame()
year = ["1997","2002","2007","2012","2017"]
for y in year:
    data_y = pd.read_csv("D:/中科院数据下载/quickstats/动物类/county/poultry/"+str(y)+".csv")
    data_all = pd.concat([data_all,data_y],axis=0)

# 完全匹配
### 与下载出来的数据data进行州县双重对应的完全匹配

In [7]:
# 定义一个核对表头的函数(完全匹配)
def label_county(standard,data):
    data["OBJECTID"] = -1
    
    # 保留的列
    col_need = ["year","Program","Sector","Commodity","Domain","Category","Group","Data Item","class_desc","OBJECTID","State","County","Value","CV (%)"]
    data = data.loc[:,col_need]
    # 创建一个字典，将州县组合
    mapping = {(row["State"].upper(),row["County"].upper()):row["OBJECTID"] for _,row in standard.iterrows()}
    # 使用apply函数创建data的OBJECTID
    data["OBJECTID"] = data.apply(lambda row:mapping.get((row["State"],row["County"]),-1),axis=1)
    return data

In [8]:
# 对data执行完全匹配
data_all = label_county(standard,data_all)

# 抽样统计
## 完全匹配中不成功的数据原因：
### 1、范围不一致，存在包含关系：比如下载的数据是Aleutians island，而标准数据名称是区分了Aleutians West和Aleutians East
### 2、存在缩写：下载的数据存在县名称的缩写，比如saint缩写成st.
### 3、表示形式不一致：比如LAPAZ与 lA Paz

In [9]:
# data2002[data2002["OBJECTID"]==-1] # 不是完全一致的县州名

# 大模型引入

In [3]:
# 用大模型完成剩余的匹配
# 设置大模型
# 引入文心一言4.0大模型
import requests
import json

API_KEY = "YrG7AyuCMXwLdgdGvvycmwgj"
SECRET_KEY = "5D9EH5u9N2m0SscWCYsNeCml4Sv6yOYw"

def baidu4(mes):
    url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro?access_token=" + get_access_token()
    
    payload = json.dumps({
        "messages": [
            {
                "role": "user",
                "content": mes
            }
        ]
    })
    headers = {
        'Content-Type': 'application/json'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload)
    
    return response.json()["result"]   

def get_access_token():
    """
    使用 AK，SK 生成鉴权签名（Access Token）
    :return: access_token，或是None(如果错误)
    """
    url = "https://aip.baidubce.com/oauth/2.0/token"
    params = {"grant_type": "client_credentials", "client_id": API_KEY, "client_secret": SECRET_KEY}
    return str(requests.post(url, params=params).json().get("access_token"))

# import openai

# def chatgpt4(prompt):
# #     openai.api_key = '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'
#     openai.api_key = 'sk-47wXB3B45tIOUPPa3e8fD47eC47d4b21AcE3Fe12C14a0487'
#     response = openai.ChatCompletion.create(
#       model="gpt-3.5-turbo-1106",  # 选择使用的模型
#       messages=[{"role": "user", "content": prompt}]
#     )

#     return response.choices[0].message['content'].strip()

def chatgpt4(mes):
    url = "https://apejhvxcd.cloud.sealos.io/v1/chat/completions"
    
    payload = json.dumps({
        "model":"gpt-4-1106-preview",
        "messages": [
            {
                "role": "user",
                "content": mes
            }
        ]
    })
    headers = {
        'Authorization': 'sk-47wXB3B45tIOUPPa3e8fD47eC47d4b21AcE3Fe12C14a0487',
        'Content-Type': 'application/json'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload)
    
    return response.json()["choices"][0]["message"]['content'].strip()

In [4]:
chatgpt4("你好")

'你好！有什么可以帮您的吗？'

## 设置相应的prompt
## 用正则表达式提取模型判断结果（OBJECTID）
## 模型对需要进行人工判断的进行标记与备注

In [11]:
# 对每一个大模型判断的函数
def ai_label(row,mapping):
    prompt = "美国的一个县名"+row["County"]+"，这个州"+row["State"]+"的县有："+str(mapping[row["State"]])+"，放回该县对应的所有可能的数值，只发结果"
    ai_reply = chatgpt4(prompt)
    # 在正则表达式处理
    pattern = re.compile(r"\d+")
    objectid_num = pattern.findall(ai_reply)
    if len(ai_reply)<60 and len(objectid_num)==1:
        objectid = objectid_num[0]
        print("字符串小于60："+ai_reply)
        return (objectid)
    else:
        print(ai_reply)
        objectid = -2
        # 说明有歧义不好判断
        return objectid,ai_reply

In [12]:
# 模糊匹配
def county_label_ai(standard,data):
    # 用嵌套字典存储州与县
    count = 0
    mapping = {}
    for _,row in standard.iterrows():
        state = row["State"].upper()
        county = row["County"].upper()
        objectid = row["OBJECTID"]
    
        if state not in mapping:
            mapping[state] = {}
        mapping[state][county] = objectid 
    while data[data["OBJECTID"]==-1].shape[0] != 0:
        print("剩余objectid为-1的行数："+str(data[data["OBJECTID"]==-1].shape[0]))
        # 只要还存在objectid=-1就执行
        objectid = ai_label(data[data["OBJECTID"]==-1].iloc[0],mapping)
        data_county = data[data["OBJECTID"]==-1].iloc[0]["County"]
        data_State = data[data["OBJECTID"]==-1].iloc[0]["State"]
        if objectid[0] != -2:
            data.loc[(data["County"]==data_county)&(data["State"]==data_State),"OBJECTID"] = objectid[0]
        else:
            data.loc[(data["County"]==data_county)&(data["State"]==data_State),"OBJECTID"] = objectid[0]-count
            data.loc[(data["County"]==data_county)&(data["State"]==data_State),"OBJECTID_NOTES"] = objectid[1]
            count = count+1
    return data

In [15]:
data_all = county_label_ai(standard,data_all)

In [203]:
data_all['OBJECTID'] = pd.to_numeric(data_all['OBJECTID'], errors='coerce')  # 将非数字转换为NaN
# data_all[data_all["OBJECTID"]<0].to_csv("test2.csv",encoding="utf-8")

In [16]:
# 最后按年分类保存成csv文件
for year,group in data_all.groupby("year"):
    group.to_csv("D:/中科院数据下载/quickstats/动物类/county/poultry_standard/"+str(year)+".csv",index=False,encoding="utf-8")

,year,Program,Sector,Commodity,Domain,Category,Group,Data Item,class_desc,OBJECTID,State,County,Value,CV (%),OBJECTID_NOTES
0,2000,SURVEY,CROPS,CORN,TOTAL,AREA PLANTED,FIELD CROPS,CORN - ACRES PLANTED,ALL CLASSES,-16,ALABAMA,OTHER (COMBINED) COUNTIES,"2,400",NaN,"77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88..."
1,2000,SURVEY,CROPS,CORN,TOTAL,AREA PLANTED,FIELD CROPS,CORN - ACRES PLANTED,ALL CLASSES,26,ALABAMA,COLBERT,"8,000",NaN,NaN
2,2000,SURVEY,CROPS,CORN,TOTAL,AREA PLANTED,FIELD CROPS,CORN - ACRES PLANTED,ALL CLASSES,48,ALABAMA,LAUDERDALE,"7,700",NaN,NaN
3,2000,SURVEY,CROPS,CORN,TOTAL,AREA PLANTED,FIELD CROPS,CORN - ACRES PLANTED,ALL CLASSES,49,ALABAMA,LAWRENCE,"10,500",NaN,NaN
4,2000,SURVEY,CROPS,CORN,TOTAL,AREA PLANTED,FIELD CROPS,CORN - ACRES PLANTED,ALL CLASSES,51,ALABAMA,LIMESTONE,"7,400",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102376,2000,SURVEY,CROPS,WHEAT,TOTAL,YIELD,FIELD CROPS,"WHEAT, WINTER, NON-IRRIGATED - YIELD, MEASURED...",WINTER,3147,WYOMING,NATRONA,11,NaN,NaN
102377,2000,SURVEY,CROPS,WHEAT,TOTAL,YIELD,FIELD CROPS,"WHEAT, WINTER, NON-IRRIGATED - YIELD, MEASURED...",WINTER,-34,WYOMING,OTHER (COMBINED) COUNTIES,25,NaN,"3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142..."
102378,2000,SURVEY,CROPS,WHEAT,TOTAL,YIELD,FIELD CROPS,"WHEAT, WINTER, NON-IRRIGATED - YIELD, MEASURED...",WINTER,3139,WYOMING,CONVERSE,30,NaN,NaN
102379,2000,SURVEY,CROPS,WHEAT,TOTAL,YIELD,FIELD CROPS,"WHEAT, WINTER, NON-IRRIGATED - YIELD, MEASURED...",WINTER,3142,WYOMING,GOSHEN,21,NaN,NaN
102380,2000,SURVEY,CROPS,WHEAT,TOTAL,YIELD,FIELD CROPS,"WHEAT, WINTER, NON-IRRIGATED - YIELD, MEASURED...",WINTER,3145,WYOMING,LARAMIE,19,NaN,NaN

In [1]:
# 下载county的动物的poultry,后续记得删除poultry total
# GROUP选择了poultry
params = {
    "source_desc":"SURVEY",
    "sector_desc":"CROPS",
    "group_desc":"FIELD CROPS",
#     "commodity_desc":["CHICKENS","DUCKS","EGGS","MEAL","POULTRY BY-PRODUCT MEALS",
#                      "POULTRY FATS","POULTRY TOTALS","POULTRY, OTHER","TURKEYS"],
#     "statisticcat_desc":["INVENTORY"],
#     "short_desc":["CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN HEAD",
#                   "CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB / HEAD, LIVE BASIS",
#                  "CHICKENS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB, LIVE BASIS",
#                  "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN HEAD",
#                   "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB / HEAD, LIVE BASIS",
#                  "TURKEYS, YOUNG, SLAUGHTER, FI - SLAUGHTERED, MEASURED IN LB, LIVE BASIS"],
    "agg_level_desc":"COUNTY",
    "year":"1957",
#     "state_name":"PENNSYLVANIA"
}

In [20]:
stat.get_par(params)

TypeError: unhashable type: 'dict'